### ISSUE TITLE
Basic example immediately exits when user detected

### ISSUE THREAD

**Issue by chriskilding** [bengfarrell/nuimotion#10]
Hi again,

I'm back, now on a Windows box with Kinect + Openni2 + Nite2. Nuimotion seems to compile and run, to the point that it lights up the Kinect IR sensor at least, so it's managed to make the connection through the native code to the hardware.

However I am finding that, as soon as I jump in front of the depth camera and Nite sees me, the basic.js node app then immediately exits. The trace from beginning to end is as follows:

```
Nui Motion Initialize
Initialize Depth Camera
Start moving around to get detected...
OpenNI/NITE processing complete
Shutdown NITE
```

I don't see any exceptions thrown, but something doesn't seem right - I assume you didn't intend for basic.js to shut down immediately?

**Comment by chriskilding** [comment]
FWIW I needed to apply a few hacks to get it working on Windows - see [my fork](https://github.com/themasterchef/nuimotion) for more information

**Comment by bengfarrell** [comment]
You rock, thanks for providing that info. Would have responded sooner, but you caught me in the middle of a cross country move. I won't have my Kinect or Xtion for another week - so I can't check this out now. On the upshot, I'll be  getting a Mac for work soon and I can revisit building on every possible platform (Windows, Ubuntu, and OSX). Looking forward to resolving that build/install issue we found and resolving what you found on Windows.

Glad you got it working, hopefully it will be painless to merge your changes and keep all the platforms working
