### ISSUE TITLE
License type? 

### ISSUE THREAD

**Issue by kinifi** [bengfarrell/nuimotion#11]
I'm not sure if you are just blanketing NUIMotion under the same license that NiTE and OpenNI use but it would be great to get some clarification on this.

**Comment by bengfarrell** [comment]
no problem - I'm not extremely familiar with licenses, but I think the MIT license is the friendliest to use. So I chose that. I'm not distributing OpenNI or NiTE with this project - it's just a requirement, so those core libraries can still fall under the Apache license as Primesense intends and I wouldn't think affects this project.

Does that make sense?
