### ISSUE TITLE
Where to download NITE?

### ISSUE THREAD

**Issue by thevinci** [bengfarrell/nuimotion#18]

**Comment by bengfarrell** [comment]
Hey, sorry, but Apple bought Primesense and shut everything down this past April. I was hoping they'd keep the website up. NiTE was never open source,so I probably shouldn't publish, but if youd like to get in touch at ben@benfarrell.com I might be able to help you out

**Comment by thevinci** [comment]
I was able to find the libraries at this link - https://www.youtube.com/watch?v=m5uTH3S9P9g. In the description, he hosted them at Google Drive. Thank you for the great work, Ben!
