### ISSUE TITLE
Is the program suppose to end when the user exits?

### ISSUE THREAD

**Issue by thevinci** [bengfarrell/nuimotion#19]
Is there a way I can make it run indefinitely? I've tested out the quickstart scripts and they stop when the user exists from the screen.

**Comment by thevinci** [comment]
Ok. I found your blog post about node-gyp and I went into the source and edited your C++. I hope I didn't break anything. I disabled your "keepWorkerRunning".

**Comment by bengfarrell** [comment]
Cool, glad you were able to do what you want. You must be doing something in Node-Webkit or Atom-Shell if you're exiting from a screen. I actually hadn't tried that yet. Last I seriously worked on this project, I don't think either of those were really available - I had just started the process and sent info through web sockets.
