### ISSUE TITLE
hi about openni

### ISSUE THREAD

**Issue by xhava** [bengfarrell/nuimotion#8]
well my question is that if i have to install Openni on my fedora or just i have to download it and put the drivers into my nodejs proyect . please someone could help me

**Comment by bengfarrell** [comment]
I believe you may need to do both. I answered another ticket where we found that OpenNI2 and NiTE2 need to be installed for the build process.

Installing will place a couple files in your /use/lib folder: libopenni2.so and libnite2.so

The build process points to these files for a successful build.

When I get a chance to look into this, I'd prefer to avoid having to rely on the install, but for now an install is necessary (unless you manually take those two files from the OpenNI redistributable files and drop them in that folder yourself).

During runtime of your Node.js app, those redistributable folders I mention on the wiki must be included at your root.

So to answer your question, both for now, and I will work to see that installation isn't a required step.
