### ISSUE TITLE
error

### ISSUE THREAD

**Issue by xhava** [bengfarrell/nuimotion#9]
someone knows about this .

gyp: binding.gyp not found (cwd: /home/xhava/proyectornodejs/kinectrobot/node_modules/nuimotion/src) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/node-gyp/lib/configure.js:424:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Linux 3.9.11-200.fc18.x86_64
gyp ERR! command "node" "/usr/bin/node-gyp" "configure" "rebuild"
gyp ERR! cwd /home/xhava/proyectornodejs/kinectrobot/node_modules/nuimotion/src
gyp ERR! node -v v0.10.13
gyp ERR! node-gyp -v v0.10.9
gyp ERR! not ok

**Comment by bengfarrell** [comment]
Hi, try running node-gyp from the nuimotion folder instead of the nuimotion/src folder.  It looks like it just can't find the binding.gyp file that controls/configures the build
